---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: motus
spec:
  ingressClassName: nginx
  rules:
    - host: motus.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: motus
                port:
                  name: http
